[package]
name = "asbb-rules"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ASBB rules component"

[dependencies]
asbb-core = { path = "../asbb-core" }
anyhow.workspace = true
